### ISSUE TITLE
Hamburger menu does not work after pushing to the Internet?

### ISSUE THREAD

**Issue by SachinPendse** [victoriadrake/hugo-theme-introduction#195] opened 2020-02-14 06:07 UTC
Hi Victoria, 

Sorry to bother you again, and thanks for all the help. I am astounded by how responsive you are here, and am so appreciative. I am trying to finish up formatting my website and I realized that when the page is small enough that the menu collapses to the hamburger format (such as on mobile), clicking it does not seem to display the menu. You can observe the behavior [here](http://sachinpendse.github.io/). 

When investigating, I also realized that this is A. not happening when I run with "hugo server" locally, and B. there are some errors that come up in the console on the Internet, as below. 

<img width="1270" alt="Screen Shot 2020-02-14 at 12 56 14 AM" src="https://user-images.githubusercontent.com/6971883/74505692-d35f8d80-4ec5-11ea-9b6f-c3bfcee912e2.png">

Do you have any idea on things I can do to fix this issue? Like [the](https://github.com/victoriadrake/hugo-theme-introduction/issues/187) [others](https://github.com/victoriadrake/hugo-theme-introduction/issues/142) who have encountered a similar issue, I tried adding to the .gitattributes file and also taking out the integrity part of the HTML, but neither seemed to work for me. Do I need to add some kind of inclusion of Bootstrap or JQuery or something in the HTML maybe? Would love any advice you have!

**Comment by victoriadrake** [comment] 2020-02-14 16:29
Hi Sachin,

This appears to be a different issue from #187. Thank you for the error screenshot, that was very helpful!

The feedback points to a [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) block that appears to be caused by your site domain configuration. My initial suspicion is that `http://sachinpendse.in` is not the same origin as `http://www.sachinpendse.in` due to the subdomain. This [further reading on same-origin](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy) may help.

What service are you using to host your site?

**Comment by SachinPendse** [comment] 2020-02-14 21:03
Hi Victoria, thank you again for your quick response and your clear passion for educating beginners. It is really really appreciated. I am using Google Domains for the domain, and Github Pages for web hosting.

**Comment by victoriadrake** [comment] 2020-02-18 03:18
If you’ve [configured your apex custom domain](https://help.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain) correctly with GitHub pages, I’m not sure why this would be happening. 

Please check the links I mentioned, and let me know if the problem still occurs. If so, you can try the workaround I wrote up in #187 that removes the integrity feature.

**Comment by SachinPendse** [comment] 2020-02-19 22:09
Hi Victoria, thank you so much for your help! It is much appreciated. Unfortunately it appears like the issue is still occurring, even with a couple of different fixes I tried. 

I tried using the fix in #187 (changing the CSS file in /layouts/partials/head/css.html to remove the integrity attribute). That did not seem to work, so I replaced all the .js/.css files with CDN versions in the index.html file as a test to see if that would make things work. Unfortunately, this did not work --- even though the developer console does not show any errors, the hamburger menu still does not work when the site is resized/mobile (you can see the site here at [sachinpendse.in](sachinpendse.in) if curious). 

**Do you have any thoughts on how I can proceed with debugging?** I've checked and the apex custom domain is correctly configured. Also checked out everything with same-origin and seems to be fine regardless of whether www is included or not. Again, thank you for all of your help :)

**Comment by SachinPendse** [comment] 2020-02-19 23:19
Ah I was able to fix it --- turns out I had to

A. Remove the integrity feature from all of the JS/CSS

B. Replace with CDN links

C. Make sure to include the local JS file starting with "bundle.e69..." (but without integrity) which has the hamburger click JS

**Comment by SachinPendse** [comment] 2020-02-19 23:45
I disabled integrity in all the files that create the <script> lines as well, and this seemed to fix the issue. I'm still not sure why this would be an issue, but the website works now.

**Comment by victoriadrake** [comment] 2020-02-29 15:21
I still see CORS errors in the console for the carousel scripts (that your site isn't using, so no big deal for right now) that I think stem from the `www` in your domain. I'd double check that your domain is consistent across the places you configure it - DNS with Google, the settings tab of your GitHub Pages repo, the CNAME file, and the config file for your Hugo site.

In any case, I'm glad it's working for the meantime. I'll go ahead and close this issue - feel free to reopen if needed.

**Closed by victoriadrake** 2020-02-29 15:21 UTC
Labels: in progress
