### ISSUE TITLE
configuring themeStyle to dark does not work

### ISSUE THREAD

**Issue by deyangeor** [victoriadrake/hugo-theme-introduction#269] opened 2020-12-19 16:54 UTC
Hello,

I like the theme very much, so thank you for sharing. :) Below is the description of my issue, but if you need any further details, please tell.

**Describe the bug**
Configuring dark theme does not seem to work

**To Reproduce**
In config.toml set

[params]
    themeStyle                   = "dark"    

**Expected behavior**
The generated website to be ... dark

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox 
 - Version 84.0

**Smartphone (please complete the following information):**
Irrelevant

**Additional context**
N/A

**Comment by MyGiHu** [comment] 2020-12-20 21:49
Hi,

I couldn't reproduce the issue with the exsample site. Are the changes in the config.toml saved and is Hugo rebuilding the website?

**Comment by GeoffreySaxena** [comment] 2020-12-25 06:54
I'm facing a similar issue, I've set the theme to dark mode, Hugo rebuilding the website too.
All the other changes take place except for this.

**Comment by MyGiHu** [comment] 2020-12-27 14:08
I observed this issue with the not extended version of Hugo. Only the extended version can process sass (style) files.
You can check your version of Hugo by running "hugo version". The output string should contain the word extended.
Installing the extended version of Hugo should fix this issue.

**Comment by victoriadrake** [comment] 2020-12-31 13:09
I think @MyGiHu is correct. I'm closing this for now, @deyangeor feel free to reopen if your issue is not resolved.

**Closed by victoriadrake** 2020-12-31 13:09 UTC
Labels: good first issue, help wanted

**Comment by deyangeor** [comment] 2021-01-15 17:02
Hello,

I am sorry, but I was away for quite some time.

I am writing this to confirm that having the extended version "renders" the dark mode ... for future readers, you know.

Thanks a lot.
D
